name: elbek
description: CV for elbek
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_builder: ^0.7.0
  simple_gradient_text: ^1.3.0
  google_fonts: ^6.1.0
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.1.14
  another_stepper: ^1.2.2
  flutter_devicon: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  teledart: ^0.6.1
  youtube_explode_dart: ^2.0.2
  dio: ^5.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.jpeg"
flutter:
  uses-material-design: true

  assets:
    - assets/
